### ISSUE TITLE
Bumper formatting JSON files

### ISSUE THREAD

**Issue by AlecRust** [release-it/bumper#34] opened 2023-07-25 18:42 UTC
e.g. this config
```json
{
  "plugins": {
    "@release-it/bumper": {
      "out": [
        {
          "file": "src/block.json",
          "path": "version"
        }
      ]
    }
  }
}
```

Or
```json
{
  "plugins": {
    "@release-it/bumper": {
      "out": ["src/block.json"]
    }
  }
}
```

While it updates the version in the following JSON, it also reformats the `keywords` property. Examples follow.

Before:
```json
{
  "version": "1.0.0",
  "keywords": ["video", "youtube", "vimeo", "embed", "player", "protected"],
}
```

After:
```json
{
  "version": "1.0.1",
  "keywords": [
    "video",
    "youtube",
    "vimeo",
    "embed",
    "player",
    "protected"
  ]
}
```

This reformatting of JSON is unexpected and causes issues with Prettier i.e. my `npm run lint` now fails after the release commit. To work around this issue I'm needing to manually re-format the file as part of the release i.e.

```json
{
  "hooks": {
    "after:bump": [
      "npx prettier --write src/block.json"
    ]
  }
}
```

Another workaround I have is to remove the `--no-verify` flag I have as part of the config, and allow the file changes in the release commit to be processed by Prettier as part of the project's commit hooks.

Either way the point is I expected bumper to just change the version, not change the formatting of JSON files.

**Comment by webpro** [comment] 2023-07-29 08:17
The issue is that JSON files have to be read and parsed, and thus stringified back into the file. It detects and re-applies indentation, but other than that it's a simple `JSON.stringify`.

If the bumper plugin would follow your recommendation it would have text-based replacement, e.g. with regular expressions, which imho isn't the right tool for the job. Or detect Prettier config, but that's also not this plugin's job. I think your solution is fine, it's not unusual to apply formatting after some tool modified a file.

That's why I'm going to close this issue.

**Closed by webpro** 2023-07-29 08:17 UTC
